"""job content fingerprint

Revision ID: 9a63e66607b8
Revises: a3d5adaf0ad1
Create Date: 2026-09-23 17:45:23.759980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a63e66607b8'
down_revision: Union[str, None] = 'a3d5adaf0ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows; the ORM Python default covers
    # new rows. SQLite has no DROP DEFAULT, the inert default stays.
    op.add_column(
        'ingestion_jobs',
        sa.Column('content_sha', sa.String(length=64), server_default='', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_jobs', 'content_sha')
    # ### end Alembic commands ###
