"""provenance and notification metadata

Revision ID: a3d5adaf0ad1
Revises: 6ef0217bacd2
Create Date: 2026-09-23 15:25:17.685723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d5adaf0ad1'
down_revision: Union[str, None] = '6ef0217bacd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_jobs', sa.Column('attempts', sa.Integer(), nullable=False))
    op.add_column('notifications', sa.Column('severity', sa.String(length=10), nullable=False))
    op.add_column('notifications', sa.Column('ingestion_id', sa.String(length=36), nullable=False))
    op.add_column('notifications', sa.Column('evidence_ids_json', sa.Text(), nullable=False))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'evidence_ids_json')
    op.drop_column('notifications', 'ingestion_id')
    op.drop_column('notifications', 'severity')
    op.drop_column('ingestion_jobs', 'attempts')
    # ### end Alembic commands ###
