from __future__ import annotations

import datetime as dt
from enum import Enum
from uuid import uuid4

from pydantic import BaseModel, Field


class NotificationType(str, Enum):
    CONTRADICTION = "CONTRADICTION"
    RELATED_WORK = "RELATED_WORK"
    STALE_DECISION = "STALE_DECISION"
    MISSING_OWNER = "MISSING_OWNER"
    NEW_INSIGHT = "NEW_INSIGHT"
    CONTEXT_FOUND = "CONTEXT_FOUND"


class NotificationPriority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class Notification(BaseModel):
    """A notification generated by an AI agent."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    type: NotificationType
    priority: NotificationPriority = NotificationPriority.MEDIUM
    title: str
    message: str = ""
    related_node_ids: list[str] = Field(default_factory=list)
    is_read: bool = False
    created_at: dt.datetime = Field(default_factory=dt.datetime.utcnow)
    metadata: dict = Field(default_factory=dict)


class NotificationCreate(BaseModel):
    """Schema for creating a notification (without auto-generated fields)."""

    type: NotificationType
    priority: NotificationPriority = NotificationPriority.MEDIUM
    title: str
    message: str = ""
    related_node_ids: list[str] = Field(default_factory=list)
    metadata: dict = Field(default_factory=dict)


class NotificationRead(BaseModel):
    """API view of a persisted notification."""

    id: str
    type: str
    priority: str
    severity: str
    title: str
    message: str = ""
    related_node_ids: list[str] = Field(default_factory=list)
    ingestion_id: str = ""
    evidence_ids: list[str] = Field(default_factory=list)
    is_read: bool = False
    created_at: dt.datetime | None = None
    read_at: dt.datetime | None = None


class NotificationExplanation(BaseModel):
    """Deterministic answer to 'why was this notification created?'."""

    notification: NotificationRead
    node_titles: list[str] = Field(default_factory=list)
    edge_labels: list[str] = Field(default_factory=list)
